### ISSUE TITLE
libkunet.so not found

### ISSUE THREAD

**Issue by kuruonur1** [denizyuret/KUnet.jl#5]
using KUnet was complaining "missing libraries" for GPU support.
I had to change KUnet.jl:8  lpath = [Pkg.dir("KUnet/cuda")] -> lpath = [Pkg.dir("KUnet/src")]  to make it work.

**Comment by quaertym** [comment]
Related https://github.com/denizyuret/KUnet.jl/pull/3

**Comment by denizyuret** [comment]
KUnet/cuda is no longer needed.  libkunet.so is compiled under and used from the src directory.  Can you give more details of what did not work?

**Comment by denizyuret** [comment]
OK, Onur was right all along.  I don't know how that path went back to KUnet/cuda.  Fixed now.  Should be KUnet/src.  New release v0.1.2.
