### ISSUE TITLE
drop between pool and conv gives memory error

### ISSUE THREAD

**Issue by denizyuret** [denizyuret/KUnet.jl#8]
Here is an example net for mnist:
```
# This one gives a memory bug after epoch 7:                                                                                                                                                                       
# net = [Drop(0.2), Conv(5,5,1,20), Bias(20), Relu(), Pool(2),                                                                                                                                                     
#        Drop(0.5), Conv(5,5,20,50), Bias(50), Relu(), Pool(2),                                                                                                                                                    
#        Drop(0.5), Mmul(500,800), Bias(500), Relu(),                                                                                                                                                              
#        Drop(0.5), Mmul(10,500), Bias(10), XentLoss()]                                                                                                                                                            
```

We get:
```
WARNING: CUDA error triggered from:

 in checkerror at /mnt/home/dyuret/src/kunet/dbg/v0.3/CUDArt/src/libcudart-6.5.jl:17
 in free at /mnt/home/dyuret/src/kunet/dbg/v0.3/CUDArt/src/pointer.jl:48
 in _start at ./client.jl:405error in running finalizer: "an illegal memory access was encountered"
```

Why are we garbage collecting?  The position in code is in net.jl:62 (train)
```
        xx = x2b(xx, x, b:e)
```

There should not be any allocation / gc happening here..

It is the first two Drops that are responsible.  If we have just the last two Drops we don't get the error.

**Comment by samanzia** [comment]
I get the following error before training on the same net as mentioned above:

ERROR: assertion failed: issimilar(dy,l.xdrop)
 in back at /mnt/home/szia13/.julia/v0.3/KUnet/src/drop.jl:21
 in back at /mnt/home/szia13/.julia/v0.3/KUnet/src/net.jl:25
 in backprop at /mnt/home/szia13/.julia/v0.3/KUnet/src/net.jl:34
 in train at /mnt/home/szia13/.julia/v0.3/KUnet/src/net.jl:64
 in anonymous at util.jl:16
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
while loading /mnt/kufs/scratch/szia13/mnisttst.jl, in expression starting on line 15

**Comment by denizyuret** [comment]
This seems to be fixed in latest version, closing.  Please reopen if you find an error.
