### ISSUE TITLE
Conv layer not following Pool layer gives error 

### ISSUE THREAD

**Issue by samanzia** [denizyuret/KUnet.jl#9]
Here is an example from mnist:

net = [Conv(5,5,1,20), Bias(20), Relu(),Pool(2), 
       Conv(5,5,20,50), Bias(50), Relu(),  
       Mmul(500,3200), Bias(500), Relu(),
       Mmul(10,500), Bias(10), XentLoss()]

I get the following error:

ERROR: assertion failed: issimilar(dy,l.y)
 in back at /mnt/home/szia13/.julia/v0.3/KUnet/src/relu.jl:18
 in back at /mnt/home/szia13/.julia/v0.3/KUnet/src/net.jl:25
 in backprop at /mnt/home/szia13/.julia/v0.3/KUnet/src/net.jl:34
 in train at /mnt/home/szia13/.julia/v0.3/KUnet/src/net.jl:64
 in anonymous at util.jl:16
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
while loading /mnt/kufs/scratch/szia13/mnisttst.jl, in expression starting on line 15

It works fine if I omit the pooling in the first layer for example:

net = [Conv(5,5,1,20), Bias(20), Relu(), 
       Conv(5,5,20,50), Bias(50), Relu(),Pool(2),  
       Mmul(500,3200), Bias(500), Relu(),
       Mmul(10,500), Bias(10), XentLoss()]

**Comment by denizyuret** [comment]
Saman, I tested your examples with the latest code and it seems to be fixed.  Please reopen if you find an error.  Differences in convention in latest code: Conv(5,5,1,20)->Conv(20,5); Bias(20)->Bias().

**Comment by samanzia** [comment]
I checked it too, its working fine now.
